version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: adminRoot@1
#      MYSQL_DATABASE : trading
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysqldata:
